version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: next-fundamentals
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fundamentals
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
